/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;

/**
 *
 * @author yoshi
 */
public class ModulosRepor extends javax.swing.JPanel {

    /**
     * Creates new form ModulosRepor
     */
    public ModulosRepor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnReporEmp = new javax.swing.JPanel();
        lblReporEmp = new javax.swing.JLabel();
        btnSalEmp = new javax.swing.JPanel();
        lblSalEmp = new javax.swing.JLabel();
        btnPlanMes = new javax.swing.JPanel();
        lblPlanMes = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(230, 400));
        setMinimumSize(new java.awt.Dimension(230, 400));
        setPreferredSize(new java.awt.Dimension(230, 400));

        jPanel1.setBackground(new java.awt.Color(194, 222, 209));
        jPanel1.setMaximumSize(new java.awt.Dimension(230, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(230, 400));

        btnReporEmp.setBackground(new java.awt.Color(53, 66, 89));
        btnReporEmp.setMaximumSize(new java.awt.Dimension(230, 50));
        btnReporEmp.setMinimumSize(new java.awt.Dimension(230, 50));
        btnReporEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReporEmpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReporEmpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReporEmpMouseExited(evt);
            }
        });

        lblReporEmp.setFont(new java.awt.Font("SF UI Display", 1, 16)); // NOI18N
        lblReporEmp.setForeground(new java.awt.Color(255, 255, 255));
        lblReporEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReporEmp.setText("Reporte de Empleados");

        javax.swing.GroupLayout btnReporEmpLayout = new javax.swing.GroupLayout(btnReporEmp);
        btnReporEmp.setLayout(btnReporEmpLayout);
        btnReporEmpLayout.setHorizontalGroup(
            btnReporEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnReporEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReporEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnReporEmpLayout.setVerticalGroup(
            btnReporEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnReporEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReporEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnSalEmp.setBackground(new java.awt.Color(53, 66, 89));
        btnSalEmp.setMaximumSize(new java.awt.Dimension(230, 50));
        btnSalEmp.setMinimumSize(new java.awt.Dimension(230, 50));
        btnSalEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalEmpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalEmpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalEmpMouseExited(evt);
            }
        });

        lblSalEmp.setFont(new java.awt.Font("SF UI Display", 1, 16)); // NOI18N
        lblSalEmp.setForeground(new java.awt.Color(255, 255, 255));
        lblSalEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalEmp.setText("Salario de Empleados");

        javax.swing.GroupLayout btnSalEmpLayout = new javax.swing.GroupLayout(btnSalEmp);
        btnSalEmp.setLayout(btnSalEmpLayout);
        btnSalEmpLayout.setHorizontalGroup(
            btnSalEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSalEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnSalEmpLayout.setVerticalGroup(
            btnSalEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSalEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnPlanMes.setBackground(new java.awt.Color(53, 66, 89));
        btnPlanMes.setMaximumSize(new java.awt.Dimension(230, 50));
        btnPlanMes.setMinimumSize(new java.awt.Dimension(230, 50));
        btnPlanMes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlanMesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPlanMesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPlanMesMouseExited(evt);
            }
        });

        lblPlanMes.setFont(new java.awt.Font("SF UI Display", 1, 16)); // NOI18N
        lblPlanMes.setForeground(new java.awt.Color(255, 255, 255));
        lblPlanMes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlanMes.setText("Planilla por Mes");

        javax.swing.GroupLayout btnPlanMesLayout = new javax.swing.GroupLayout(btnPlanMes);
        btnPlanMes.setLayout(btnPlanMesLayout);
        btnPlanMesLayout.setHorizontalGroup(
            btnPlanMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPlanMesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPlanMes, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnPlanMesLayout.setVerticalGroup(
            btnPlanMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPlanMesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPlanMes, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnReporEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPlanMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSalEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnReporEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnSalEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnPlanMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporEmpMouseClicked
        ModuloReportesEmp mRepEmp = new ModuloReportesEmp();

        mRepEmp.setSize(new Dimension(970, 600));
        mRepEmp.setLocation(0,0);
        Principal.PanelPrincipal.removeAll();
        Principal.PanelPrincipal.add(mRepEmp,BorderLayout.CENTER);
        Principal.PanelPrincipal.revalidate();
        Principal.PanelPrincipal.repaint();
    }//GEN-LAST:event_btnReporEmpMouseClicked

    private void btnReporEmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporEmpMouseEntered
        btnReporEmp.setBackground(new Color(0, 0, 0));
        lblReporEmp.setFont(new Font("SF UI Display", Font.BOLD, 18));
    }//GEN-LAST:event_btnReporEmpMouseEntered

    private void btnReporEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporEmpMouseExited
        btnReporEmp.setBackground(new Color(53,66,89));
        lblReporEmp.setFont(new Font("SF UI Display", Font.BOLD, 16));
    }//GEN-LAST:event_btnReporEmpMouseExited

    private void btnPlanMesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlanMesMouseClicked
        ModuloReportesPlanMes mRepPlanMes = new ModuloReportesPlanMes();

        mRepPlanMes.setSize(new Dimension(970, 600));
        mRepPlanMes.setLocation(0,0);
        Principal.PanelPrincipal.removeAll();
        Principal.PanelPrincipal.add(mRepPlanMes, BorderLayout.CENTER);
        Principal.PanelPrincipal.revalidate();
        Principal.PanelPrincipal.repaint();
    }//GEN-LAST:event_btnPlanMesMouseClicked

    private void btnPlanMesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlanMesMouseEntered
        btnPlanMes.setBackground(new Color(0, 0, 0));
        lblPlanMes.setFont(new Font("SF UI Display", Font.BOLD, 18));
    }//GEN-LAST:event_btnPlanMesMouseEntered

    private void btnPlanMesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlanMesMouseExited
        btnPlanMes.setBackground(new Color(53,66,89));
        lblPlanMes.setFont(new Font("SF UI Display", Font.BOLD, 16));
    }//GEN-LAST:event_btnPlanMesMouseExited

    private void btnSalEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalEmpMouseClicked
        ModuloReportesSalEmp mRepSalEmp = new ModuloReportesSalEmp();

        mRepSalEmp.setSize(new Dimension(970, 600));
        mRepSalEmp.setLocation(0,0);
        Principal.PanelPrincipal.removeAll();
        Principal.PanelPrincipal.add(mRepSalEmp, BorderLayout.CENTER);
        Principal.PanelPrincipal.revalidate();
        Principal.PanelPrincipal.repaint();
    }//GEN-LAST:event_btnSalEmpMouseClicked

    private void btnSalEmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalEmpMouseEntered
        btnSalEmp.setBackground(new Color(0, 0, 0));
        lblSalEmp.setFont(new Font("SF UI Display", Font.BOLD, 18));
    }//GEN-LAST:event_btnSalEmpMouseEntered

    private void btnSalEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalEmpMouseExited
        btnSalEmp.setBackground(new Color(53,66,89));
        lblSalEmp.setFont(new Font("SF UI Display", Font.BOLD, 16));
    }//GEN-LAST:event_btnSalEmpMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnPlanMes;
    private javax.swing.JPanel btnReporEmp;
    private javax.swing.JPanel btnSalEmp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPlanMes;
    private javax.swing.JLabel lblReporEmp;
    private javax.swing.JLabel lblSalEmp;
    // End of variables declaration//GEN-END:variables
}
